### ISSUE TITLE
Native text selection

### ISSUE THREAD

**Issue by cuddeford** [groupnoto/semicolon#3]
The Ace editor doesn't support native text selection on either iOS or Android, but the API does support text selection and clipboard behaviour.

**Comment by nicknikolov** [comment]
This is basic stuff, should be in 0.0.1 I think. Or at least some progress on it. But if the API allows it then I don't think it will be hard to implement.

**Comment by cuddeford** [comment]
This has been fixed since the editor was switched over from Ace to CodeMirror.
