### ISSUE TITLE
Save files

### ISSUE THREAD

**Issue by nicknikolov** [groupnoto/semicolon#4]
We have to give some thought to this. If our app is a web app - where do we keep files? We could have everything on a web server but that would be crazy. It means you can't work offline. So how do we store files locally in a web app? As far as I know there are some databases that work offline and can sync with the server when the app goes online, that could be an option - I forgot the name of the database I'm gonna add it here when I Google more on this topic. I guess the other option would be to look at Phonegap and similar things that can access native APIs. I'd guess that's how people store files too.
Anyway - we need some research and options on this. I'd love to get it done for 0.0.1.

**Comment by cuddeford** [comment]
Manifest files are used to save files locally for web apps.

**Comment by cuddeford** [comment]
Preferable to (or in conjunction with) Manifest files, localstorage seems to be the best option:

http://diveintohtml5.info/storage.html
