### ISSUE TITLE
Running a sketch

### ISSUE THREAD

**Issue by nicknikolov** [groupnoto/semicolon#5]
So we can now render processing code. But how do we show it on the phone? Right now everything is one HTML and it's fine on desktop obviously but we need to figure out how it would work on the phone.
Some div tag that we show and hide? We scroll up and down? Unlike the native app here the editor and the sketch are both HTML so we can get more creative with the design... or keep it simple I don't know.

**Comment by cuddeford** [comment]
For portrait, use the Run button to display a fullscreen render.
For landscape the live-coding interface is active, with code on the left and renderer on the right.
Just an idea.

**Comment by nicknikolov** [comment]
Yeah, that sounds good for now. Later on we can go crazy with translucent sketches over the editor and whatnot. Anyway, since I made rendering work I guess I'll work on this next.

**Comment by nicknikolov** [comment]
I'll close this one since we got it running.
